username: "" # 用户名
password: "" # 密码
ai:
  base_url: "https://api.deepseek.com/v1"
  model: "deepseek-chat"
  apikey: "" # https://platform.deepseek.com/usage(默认deepseek)
driver_type: "edge" # 支持firefox,chrome,edge[默认edge]
sleep_time: 10 # 单位: s